/* CARGA INICIAL */
insert into PERMISSOES (NOME, CRIAR, LER, ATUALIZAR, DELETAR, ADMINISTRADOR, DATA_CRIACAO, DATA_ALTERACAO) values ('Administrador', 1, 1, 1, 1, 1, (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));
insert into PERMISSOES (NOME, CRIAR, LER, ATUALIZAR, DELETAR, ADMINISTRADOR, DATA_CRIACAO, DATA_ALTERACAO) values ('Leitor', 0, 1, 0, 0, 0, (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));
insert into PERMISSOES (NOME, CRIAR, LER, ATUALIZAR, DELETAR, ADMINISTRADOR, DATA_CRIACAO, DATA_ALTERACAO) values ('Editor', 1, 1, 1, 1, 0, (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));

-- Senha do admin: admin
insert into CADASTRADORES (USUARIO, SENHA, ATIVO, COD_PERMISSAO, DATA_CRIACAO, DATA_ALTERACAO) values ('admin', '21232F297A57A5A743894A0E4A801FC3', 1, (select CODIGO from PERMISSOES where NOME = 'Administrador'), (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));

-- Senha do leitor: leitor
insert into CADASTRADORES (USUARIO, SENHA, ATIVO, COD_PERMISSAO, DATA_CRIACAO, DATA_ALTERACAO) values ('leitor', '32724E2DEB219FCB7518B10AEB483A15', 1, (select CODIGO from PERMISSOES where NOME = 'Leitor'), (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));

-- Senha do editor: editor
insert into CADASTRADORES (USUARIO, SENHA, ATIVO, COD_PERMISSAO, DATA_CRIACAO, DATA_ALTERACAO) values ('editor', '5AEE9DBD2A188839105073571BEE1B1F', 1, (select CODIGO from PERMISSOES where NOME = 'Editor'), (select CURRENT_DATE from DUAL), (select CURRENT_DATE from DUAL));